### ISSUE TITLE
crash: chunk size must be non-zero

### ISSUE THREAD

**Issue by memark** [uiua-lang/uiua#255]
Uiua 0.2.0, MacOS 14.1.1, MBP M1 Max

```
❯ cat mre.ua
PatternRow ← |1 ↻1 ▽∶ [0 1 0 ¯1] ×[1 1 1 1]
PatternMatrix ← |1 ∺(↯⊙PatternRow) ⊃(⊂[])(+1⇡)

SolvePartOne! ← |1 (
  ∵parse
  ∶ PatternMatrix ⧻.
  ⍥(♭≡([◿10⌵/+]) ∺×,) ^0
  ↙8 /$"__" ⊙;
)

SolvePartOne!(100) "80871224585914546619083218645595"
```

```
❯ uiua run mre.ua

The application panicked (crashed).
Message:  chunk size must be non-zero
Location: /Users/memark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiua-0.2.0/src/algorithm/pervade.rs:348

Backtrace omitted.

Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Error: The interpreter has crashed!
  Hooray! You found a bug!
  Please report this at http://github.com/uiua-lang/uiua/issues/new

  code:
  mre.ua:7:18
  PatternRow ← |1 ↻1 ▽∶ [0 1 0 ¯1] ×[1 1 1 1]
  PatternMatrix ← |1 ∺(↯⊙PatternRow) ⊃(⊂[])(+1⇡)

  SolvePartOne! ← |1 (
    ∵parse
    ∶ PatternMatrix ⧻.
    ⍥(♭≡([◿10⌵/+]) ∺×,) ^0
    ↙8 /$"__" ⊙;
  )

  SolvePartOne!(100) "80871224585914546619083218645595"
  at mre.ua:7:18
7 |   ⍥(♭≡([◿10⌵/+]) ∺×,) ^0
```

after about 40 s.

**Comment by kaikalii** [comment]
The particular crash you encountered was fixed a little while ago. That fix will be available in the release I am putting out today.
However, when running your code with the fix, it fails with 
```
memory allocation of 274877906960 bytes failed
```
You may want to test your code with a smaller input to make sure it is not doing something weird.

**Comment by memark** [comment]
Actually I still get the same error with Uiua 0.3.0, just a different line number.

```
The application panicked (crashed).
Message:  chunk size must be non-zero
Location: /Users/memark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiua-0.3.0/src/algorithm/pervade.rs:353
```

But yeah, I'm not expecting this code to be fully functional. Just trying some things out.

**Comment by kaikalii** [comment]
Hmm, this must be a platform dependent bug, because I still get a memory allocation error.

**Comment by memark** [comment]
Maybe you have too little memory. :)

Any way I can better help out getting to the bottom of it?

**Comment by kaikalii** [comment]
If you could find a minimum example, that may help.

**Comment by memark** [comment]
I'm working on it. Here is what I'm down to right now:

```
: ⊞=..⇡32
⍥(&p@. ♭≡([/+]) ∺× ,) 5
```

**Comment by memark** [comment]
However, changing 32 to 33 above gives a different exception(!)

```
The application panicked (crashed).
Message:  assertion failed: end <= self.end
Location: /Users/memark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiua-0.3.0/src/array.rs:250
```

**Comment by memark** [comment]
And, when running in a small docker container, I also end up with out-of-memory instead.

**Comment by kaikalii** [comment]
I've just pushed a potential fix to `main`.
I was using `u32`s as bounds for array slices, which were likely getting maxed out.
I've changed them to `usize`s.
That being said, you are still creating arrays that are gigabytes in size, so I don't know if weird behavior like this can be avoided.

**Comment by memark** [comment]
Commit 9eb5bac solves both exceptions for me. Thanks!
